# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Datasaur Application CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_URL: https://raw.githubusercontent.com/yesasurya/datasaur-devops/main/Dockerfile
    strategy:
      matrix:
        node-version: [15.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Get the commit hash and output it for Docker image tag
      id: GET_DOCKER_IMAGE_TAG
      run: echo "::set-output name=DOCKER_IMAGE_TAG::$(git rev-parse --short $GITHUB_SHA)"
        
    - name: Download Dockerfile
      run: curl ${{ env.DOCKERFILE_URL }} --output Dockerfile
        
    - name: Build the Docker image and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: datasaur-application:${{ steps.GET_DOCKER_IMAGE_TAG.outputs.DOCKER_IMAGE_TAG }}
